[tool.poetry]
name = "aula06-bootcamp-python"
version = "0.1.0"
description = ""
authors = ["Renato Macedo <renatolmb@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
blue = "^0.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
